### ISSUE TITLE
Restoration issue

### ISSUE THREAD

**Issue by sri-05** [ossc-db/pg_rman#103]
not able to restore the pg_rman backup on remote server for postgresql

**Comment by sri-05** [comment]
Hi As per above comment (#103). 
Am able to take full  and incremental backup and restore it on single server successfully. But same backup data am not able to restore it on different server as it is giving below error:

-bash-4.2$ pg_rman restore --recovery-target-time '2018-12-27 11:21:29' -B /mnt/backup_pg_rman/ -D /var/lib/pgsql/9.4/data/ -U postgres
ERROR: cannot do restore
DETAIL: There is no valid full backup which can be used for given recovery condition.

---------------
even having full backup from pg_rman which is working on other server.And there are no logs getting generated for this issue...

**Comment by huangfumingyue** [comment]
Hi,
Can you show the output of:
pg_rman show detail -B /mnt/backup_pg_rman/

**Comment by MoonInsung** [comment]
Dear @sri-05 .

Maybe any PATH variables for the environment to restore are not set correctly.
Please check if the PATH variables for 
BACKUP_PATH, PGDATA, and ARCLOG_PATH 
are set normally.

And I apologize for this comment. 
This issue is very old, so if you don't have any opinion, I'll close the issue around June 28th.
If any comments are related to the issue after it has been closed, please reopen it.

Best regards.
Moon.
