### ISSUE TITLE
bug:when backup from standby it fail to start after restore

### ISSUE THREAD

**Issue by movead** [ossc-db/pg_rman#106]
Problem description:
When backup from standby  and i remove all data dir  before do restore.
Then i get 
`2019-02-11 15:24:47.611 CST [24420] LOG: 00000: database system was interrupted while in recovery at log time 2019-02-11 15:23:42 CST
2019-02-11 15:24:47.611 CST [24420] HINT: If this has occurred more than once some data might be corrupted and you might need to choose an earlier recovery target.
cp: cannot stat ‘/home/highgo/archive/0000000A.history’: No such file or directory
2019-02-11 15:24:48.102 CST [24420] FATAL: 22023: recovery target timeline 10 does not exist`
when i try to start database.

Reason:
The program does not backup the file '0000000A.history’'
And  it occur too, when backup from master in a special order.

My suggestion：
When do the 'pg_rman init' we can backup all 'xxxxxxxx.history' file in pg_wal to timeline_history dir.

**Comment by Frank111** [comment]
I have same problem , did you have sloved it?

**Comment by MoonInsung** [comment]
Dear @movead 

Could you explain in detail how to reproduce it?
These issues have not been reproduced in my environment.

And I apologize for this comment. 
This issue is very old, so if you don't have any opinion, I'll close the issue around June 28th.
If any comments are related to the issue after it has been closed, please reopen it.
