### ISSUE TITLE
WAL files are restored further than --recovery-target-time

### ISSUE THREAD

**Issue by jakjohnson** [ossc-db/pg_rman#123]
When performing PITR, pg_rman restores WAL files from backups that are posterior to the recovery time target.

Example:

Given the following backups,

...
2019-10-09 11:42:50  2019-10-09 11:42:54  FULL    64MB     1  OK
2019-10-09 11:40:00  2019-10-09 11:40:04  FULL    64MB     1  OK
2019-10-09 11:38:27  2019-10-09 11:38:56  FULL    64MB     1  OK

And running: 
pg_rman restore --recovery-target-time "2019-10-13 11:39:00"

INFO: restoring database files from the full mode backup "2019-10-09 11:38:27"
INFO: searching incremental backup to be restored
INFO: searching backup which contained archived WAL files to be restored
INFO: backup "2019-10-09 11:38:27" is valid
INFO: restoring WAL files from backup "2019-10-09 11:38:27"
INFO: backup "2019-10-09 11:40:00" is valid
INFO: restoring WAL files from backup "2019-10-09 11:40:00"
INFO: backup "2019-10-09 11:42:50" is valid
INFO: restoring WAL files from backup "2019-10-09 11:42:50"
...

The tool correctly finds the closest FULL backup (2019-10-09 11:38:27) and the WAL files needed (backup 2019-10-09 11:40:00) but it does not stop and keeps restoring all future valid WAL files .

**Comment by MoonInsung** [comment]
Dear @jakjohnson 

The restore of the pg_rman is based on the backup file near the time backup was completed.
Also, since it restores using the archive log with the backup file, it is normal.

And I apologize for this comment. 
This issue is very old, so if you don't have any opinion, I'll close the issue around June 28th.
If any comments are related to the issue after it has been closed, please reopen it.

Best regards.
Moon.
