### ISSUE TITLE
pg_rman.h:13:10: fatal error: postgres_fe.h:

### ISSUE THREAD

**Issue by Mrqlxdd** [ossc-db/pg_rman#129]
This error occurs when i make.
What's problem?

**Comment by WFLl** [comment]
因为pg_rman的源代码文件，依赖于postgres数据库的一些头文件，所以如果你想make的话，你需要export PATH=$PATH:/usr/local/pgsql/bin

**Comment by MoonInsung** [comment]
Dear @Mrqlxdd 

Please check if the PATH variable is set normally.
Also, please use the pg_rman that is related to the PostgreSQL using version.

And I apologize for this comment. 
This issue is very old, so if you don't have any opinion, I'll close the issue around June 28th.
If any comments are related to the issue after it has been closed, please reopen it.

Best regards.
Moon.
