### ISSUE TITLE
Regression Test fails in REL 10 Stable

### ISSUE THREAD

**Issue by ahmedelbendary** [ossc-db/pg_rman#132]
![image](https://user-images.githubusercontent.com/25745226/75684575-b8e92a80-5ca1-11ea-8244-ead520dd385f.png)

Below is the first bage from regression.diffs

![image](https://user-images.githubusercontent.com/25745226/75684884-53e20480-5ca2-11ea-8124-528f8e39503f.png)

**Comment by MoonInsung** [comment]
Dear @ahmedelbendary 

Is it possible to check again using the latest version of the pg_rman?
In the case of the latest version, all regression tests normally pass.

And I apologize for this comment. 
This issue is very old, so if you don't have any opinion, I'll close the issue around June 28th.
If any comments are related to the issue after it has been closed, please reopen it.

Best regards.
Moon.
