### ISSUE TITLE
The archive directory has been growing

### ISSUE THREAD

**Issue by Widerstehen** [ossc-db/pg_rman#133]
The archive directory has been growing. Is there a way to automatically delete WAL files that have been backed up? Anyone has experience ?

**Comment by MoonInsung** [comment]
Dear @Widerstehen 

Consider using the options of KEEP_ARCLOG_FILES and KEEP_ARCLOG_DAYS.
Please refer to the manual of the pg_rman for detailed usage.
However, since it is a deleting the archive log, 
so please be careful as it may cause side effects 
when run to restore depending on use-case(or env) it.


And I apologize for this comment. 
This issue was registered a year ago, 
so if you don't have any opinion, I'll close the issue around June 28th.
If any comments are related to the issue after it has been closed, please reopen it.

Best regards.
Moon.
