### ISSUE TITLE
pg_rman rpm installer does not allow multiple version of postgresql.

### ISSUE THREAD

**Issue by giantdba** [ossc-db/pg_rman#137]
when i install multiple version of postgresql on same server.  such as 9.6 and 11.

and then i try install pg_rman for 9.6 and 11.

but each version of pg_rman rpm clean up installed other version.

ex)
install pg_rman for 9.6
install pg_rman for 11 -> cleanup pg_rman for 9.6
install pg_rman for 9.6 -> cleanup pg_rman for 11

how can i backup both database using pg_rman?

**Comment by MoonInsung** [comment]
Dear @giantdba 

It seems to be solved by 
setting the environment variable(PATH, BACKUP_PATH, anymore) when using each version.
In other words, rather than being an issue of the pg_rman, 
it needs to setting like an environment.

And I apologize for this comment. 
This issue was registered a year ago, 
so if you don't have any opinion, I'll close the issue around June 28th.
If any comments are related to the issue after it has been closed, please reopen it.

Best regards.
Moon.
