### ISSUE TITLE
Serious problems with incremental backups

### ISSUE THREAD

**Issue by HIghGo-coder** [ossc-db/pg_rman#150]
Based on the latest version of pg_rman v1.3.11, the following problems have occurred:
     Due to code issues, we failed to make a reasonable incremental backup of the data files.
     In issue #121, a meaningless incremental backup was fixed, but the result was that our incremental backup function failed to achieve the expected results. Incremental backup is a process where the first incremental backup is based on the full backup, and the second incremental backup is based on the first incremental backup. However, due to code issues, the second incremental backup is also based on a full backup. This conflicts with the meaning of incremental backup, causing pg_rman to fail to implement incremental backup.
     My team and I are very interested in the pg_rman project, and we are also capable of fixing this problem. We have found the source of the problem.
     looking forward to your reply.

**Comment by MoonInsung** [comment]
Thank you for reporting the critical bug.
As you said, the current incremental backup of pg_rman is not normal from the second round.
It's acting like doing a differential backup.
We will prepare for the bug fix and release of this issue right after April.
Sorry for the late response.

Best regards.
Moon.

**Comment by MoonInsung** [comment]
Dear @HIghGo-coder 

Thank you again for reporting the problem.
To improve this critical error, 
we solved it by roll back to related source code.
However, I created a new issue(#154) because 
we need an improvement plan regarding the incremental backup.

If you have any other opinions, please register on issue #154.
Therefore, I will close the issue.

Best regards.
Moon.
