### ISSUE TITLE
support backup xlog from pg_xlog directory in hot_stanadby?

### ISSUE THREAD

**Issue by digoal** [ossc-db/pg_rman#44]
HI, 
   now pg_rman only backup archive xlog from archive directory, but when i backup database from hot_standby, because standby don't archive it's xlog, so i have to share archive dir between primary and standby hosts. 
  can pg_rman support backup xlog from pg_xlog dir?  so i only need to set a big wal_keep_segments with hot_standby.    
  or support it with another thread by streaming connect to standby? like pg_receviexlog, it don't need a big wal_keep_segments.    

best regards.

**Comment by amitlan** [comment]
Can I ask what PostgreSQL server version you are using?

With versions >= 9.5, you can use archive_mode = 'always' so that a standby server is able to archive the WAL segments in its own archive location.  Read more in section 25.2.9 in PostgreSQL 9.5 documentation:
https://www.postgresql.org/docs/9.5/static/warm-standby.html#CONTINUOUS-ARCHIVING-IN-STANDBY

**Comment by digoal** [comment]
thank you. i forgate that change.
