### ISSUE TITLE
Regression tests diffs in environment with resource pressure

### ISSUE THREAD

**Issue by michaelpq** [ossc-db/pg_rman#47]
```
*** /home/packages/pg_rman/expected/arc_srv_log_management.out  Sun Sep 18 03:18:28 2016
--- /home/packages/pg_rman/results/arc_srv_log_management.out   Sun Sep 18 17:38:50 2016
***************
*** 6,16 ****
  Number of existing archivelog files: 5
  do --keep-arclog-files=3
  0
! Number of remaining archivelog files: 3
  ###### LOG FILE MANAGEMENT TEST-0002 ######
  ###### keep-arclog-days only ######
  0
! Number of existing archivelog files: 5
  do --keep-arclog-days=1
  0
  Number of remaining archivelog files: 4
--- 6,16 ----
  Number of existing archivelog files: 5
  do --keep-arclog-files=3
  0
! Number of remaining archivelog files: 2
  ###### LOG FILE MANAGEMENT TEST-0002 ######
  ###### keep-arclog-days only ######
  0
! Number of existing archivelog files: 4
  do --keep-arclog-days=1
  0
  Number of remaining archivelog files: 4

======================================================================
```

Some of the internal test framework that I use is complaining about the following diff... I am not sure what to think about that. My guess is that the system is under so much I/O pressure that it didn't get the time to archive all the segments to the archive path before pg_rman had the time to grab it.

And I cannot reproduce that manually.

**Comment by amitlan** [comment]
Thanks for the report.  I cannot imagine why it may be happening right away but  will try to figure out.

From a little bit of reading the code, it seems pg_rman does wait for the necessary WAL segment files to be marked *ready* in `pg_xlog/archive_status/` in `wait_for_archive()`.  However that may not be enough, because that does not ensure anything about whether pg_rman's next steps (specifically, `delete_old_files()` that implements keep-arclog-* logic) are synchronized with the files appearing in the archive directory.  The latter is entirely the responsibility of the server's archiver process which is subject to arbitrary I/O pressure as you say.

By the way - it may obvious but we can perhaps say that the diff in test 0002 is caused because of the results of test 0001.  That is, keep-arclog-files test could keep only 2 of the 3 asked for, so the test 0002 started with one less existing WAL segment causing the diff.

**Comment by bwtakacy** [comment]
Hmm.

> My guess is that the system is under so much I/O pressure that it didn't get the time to archive all the segments to the archive path before pg_rman had the time to grab it.

I think you are right.

As @amitlan pointed out, pg_rman wait fpr WAL archive not strictly.
In the current implementation, pg_rman wait for up to 10 seconds and this value is hard-coded :(.

```
  26 #define TIMEOUT_ARCHIVE     10      /* wait 10 sec until WAL archive complete */
```

It is a possible and quick workaround to make this timeout for configurable parameter.
Although this is not a complete solution because this does not ensure the actual WAL archiving in the PostgreSQL side, users can tune this timeout for long enough in the I/O resource pressure environment.

Thought?

**Comment by michaelpq** [comment]
Ah, thanks for pointing out the part with TIMEOUT_ARCHIVE. I did not notice that first. pg_rman is not doing anything wrong at the end as ERROR exits the program and lets the user know about the problem.

However I am a bit surprised that this is the default behavior actually. I would have thought that by default pg_rman would wait for the last segment to be archived in any case as usually what matters to users is not the time it takes to take a backup, but the time to restore it and the consistency of the backup. Still I agree that having an option to configure the timeout would be nice, by default that should be infinite I think, but I am just one guy here.

As I look at the code, I'd recommend using pg_usleep() instead of plain sleep() ;)

**Comment by bwtakacy** [comment]
> However I am a bit surprised that this is the default behavior actually. I would have thought that by default pg_rman would wait for the last segment to be archived in any case as usually what matters to users is not the time it takes to take a backup, but the time to restore it and the consistency of the backup. Still I agree that having an option to configure the timeout would be nice, by default that should be infinite I think, but I am just one guy here.

Yeah, the current behavior is not good so that it might caused inconsistent backup.
This is quite a big issue for pg_rman.

@amitlan @kfuru @ooyamams 
Will discuss about this? 
I think there are two way:
1. workaround - let this timeout to be configurable,
2. improvement - change to wait the actual WAL file archiving with configurable timeout


> As I look at the code, I'd recommend using pg_usleep() instead of plain sleep() ;)

Thanks!  Will fix.

**Comment by michaelpq** [comment]
We may be able to discuss about that on Monday as well F2F.

**Comment by bwtakacy** [comment]
Is there some meetings or events ?

**Comment by amitlan** [comment]
@bwtakacy Yeah, there is a Japan Postgres developers meetup organized by Hemmi-san.  The last one was in April just before this year's PGCon, Ottawa.

**Comment by bwtakacy** [comment]
Sounds nice:)

Could you tell me when it is held and whether I can join?

**Comment by amitlan** [comment]
I am afraid there is a predetermined invitee list for making certain arrangements (like the venue).

**Comment by bwtakacy** [comment]
Oh, I see.

Then, I hope @amitlan and @michaelpq (may be attend?) will tell about this on Monday :)

**Comment by michaelpq** [comment]
Ah yes I'll be there, leaving earlier that the others though.

**Comment by bwtakacy** [comment]
@michaelpq 
I'm sorry that I want but cannot join that meeting ...

**Comment by amitlan** [comment]
This has been solved by modifying the test script (adding sleep to avoid errors caused by timing races), and there is no plan at the moment to try to fix this as a bug in the pg_rman code itself.

Thanks for the patience. :-)
